const deadlineItems = [
  {
    id: 1,
    shopId: 107,
    productId: 10704,
    marketName: "인동 채소가게",
    name: "친환경 시금치",
    weight: "300g~",
    originalPrice: 3200,
    discountRate: 26,
    discountedPrice: 2368,
    rating: 4.8,
    reviewCount: 9,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 2,
    shopId: 104,
    productId: 10405,
    marketName: "금오 버섯가게",
    name: "국내산 청경채",
    weight: "300g~",
    originalPrice: 2600,
    discountRate: 23,
    discountedPrice: 2002,
    rating: 4.72,
    reviewCount: 7,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 3,
    shopId: 106,
    productId: 10601,
    marketName: "원평 채소가게",
    name: "국내산 버섯 모둠",
    weight: "500g~",
    originalPrice: 5000,
    discountRate: 25,
    discountedPrice: 3750,
    rating: 4.86,
    reviewCount: 15,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 4,
    shopId: 102,
    productId: 10205,
    marketName: "새마을 채소가게",
    name: "국내산 애호박",
    weight: "1개",
    originalPrice: 2800,
    discountRate: 21,
    discountedPrice: 2212,
    rating: 4.76,
    reviewCount: 13,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 5,
    shopId: 108,
    productId: 10804,
    marketName: "옥계 농산물가게",
    name: "친환경 열무",
    weight: "1단",
    originalPrice: 2800,
    discountRate: 25,
    discountedPrice: 2100,
    rating: 4.79,
    reviewCount: 10,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 6,
    shopId: 105,
    productId: 10501,
    marketName: "선산봉황 과일가게",
    name: "국내산 배",
    weight: "5개입",
    originalPrice: 7000,
    discountRate: 21,
    discountedPrice: 5530,
    rating: 4.81,
    reviewCount: 16,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
];

export default deadlineItems;
