// src/components/db/orderInfo.js

const imageUrl =
    "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg";

const orderInfo = [
    {
        id: "1",
        marketName: "진골마켓",
        productName: "국내산 홍당근",
        weightLabel: "1.5kg",
        imageUrl,
        discountRate: 0.15,
        price: 3213,
        originalPrice: 3780,
        status: "IN_PROGRESS",
        stepLabel: "4.5kg",
        progress: { currentKg: 10.5, maxKg: 15 },
        dDayLabel: "D-2",
        cancellable: true,
    },
    {
        id: "2",
        marketName: "한빛시장",
        productName: "유기농 감자",
        weightLabel: "2kg",
        imageUrl,
        discountRate: 0.1,
        price: 5400,
        originalPrice: 6000,
        status: "READY_FOR_PICKUP",
        progress: { currentKg: 5, maxKg: 5 },
    },
    {
        id: "3",
        marketName: "푸른농원",
        productName: "제주 감귤",
        weightLabel: "3kg",
        imageUrl,
        discountRate: 0.2,
        price: 16000,
        originalPrice: 20000,
        status: "IN_PROGRESS",
        stepLabel: "1.0kg",
        progress: { currentKg: 14, maxKg: 15 },
        dDayLabel: "D-1",
        cancellable: true,
    },
    {
        id: "4",
        marketName: "신선마켓",
        productName: "한우 불고기",
        weightLabel: "500g",
        imageUrl,
        discountRate: 0.05,
        price: 15200,
        originalPrice: 16000,
        status: "READY_FOR_PICKUP",
        progress: { currentKg: 0.5, maxKg: 0.5 },
    },
    {
        id: "5",
        marketName: "진골마켓",
        productName: "국내산 양파",
        weightLabel: "4kg",
        imageUrl,
        discountRate: 0,
        price: 8900,
        status: "IN_PROGRESS",
        stepLabel: "2.0kg",
        progress: { currentKg: 8, maxKg: 10 },
        dDayLabel: "D-3",
        cancellable: true,
    },
    {
        id: "6",
        marketName: "해솔시장",
        productName: "참외",
        weightLabel: "1.2kg",
        imageUrl,
        discountRate: 0.12,
        price: 6600,
        originalPrice: 7500,
        status: "READY_FOR_PICKUP",
        progress: { currentKg: 1.2, maxKg: 1.2 },
    },
    {
        id: "7",
        marketName: "푸른농원",
        productName: "방울토마토",
        weightLabel: "2.5kg",
        imageUrl,
        discountRate: 0.18,
        price: 12300,
        originalPrice: 15000,
        status: "IN_PROGRESS",
        stepLabel: "0.5kg",
        progress: { currentKg: 4.5, maxKg: 5 },
        dDayLabel: "D-1",
        cancellable: true,
    },
    {
        id: "8",
        marketName: "한빛시장",
        productName: "국산 사과",
        weightLabel: "5kg",
        imageUrl,
        discountRate: 0.2,
        price: 24000,
        originalPrice: 30000,
        status: "READY_FOR_PICKUP",
        progress: { currentKg: 5, maxKg: 5 },
    },
    {
        id: "9",
        marketName: "신선마켓",
        productName: "국내산 상추",
        weightLabel: "300g",
        imageUrl,
        discountRate: 0.05,
        price: 2850,
        originalPrice: 3000,
        status: "IN_PROGRESS",
        stepLabel: "0.2kg",
        progress: { currentKg: 0.8, maxKg: 1 },
        dDayLabel: "D-4",
        cancellable: true,
    },
    {
        id: "10",
        marketName: "해솔시장",
        productName: "수박",
        weightLabel: "6kg",
        imageUrl,
        discountRate: 0.1,
        price: 16200,
        originalPrice: 18000,
        status: "READY_FOR_PICKUP",
        progress: { currentKg: 6, maxKg: 6 },
    },
];

export default orderInfo;
