// file: order-info.js
export const IN_PROGRESS_ORDERS = [
    {
        id: "101",
        marketName: "진골마켓",
        productName: "국내산 흙당근",
        weightLabel: "1.5kg",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.15,
        price: 3213,
        originalPrice: 3780,
        status: "IN_PROGRESS",
        stepLabel: "4.5kg",
        progress: { currentKg: 10.5, maxKg: 15 },
        dDayLabel: "D-2",
        cancellable: true,
    },
    {
        id: "102",
        marketName: "푸른농원",
        productName: "국내산 감자",
        weightLabel: "2kg",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.1,
        price: 5480,
        originalPrice: 6089,
        status: "IN_PROGRESS",
        stepLabel: "3.0kg",
        progress: { currentKg: 12.0, maxKg: 15 },
        dDayLabel: "D-3",
        cancellable: true,
    },
    {
        id: "103",
        marketName: "진골마켓",
        productName: "유기농 대파",
        weightLabel: "1단",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.08,
        price: 1980,
        originalPrice: 2152,
        status: "IN_PROGRESS",
        stepLabel: "6.0단",
        progress: { currentKg: 9.0, maxKg: 15 },
        dDayLabel: "D-4",
        cancellable: true,
    },
    {
        id: "104",
        marketName: "신선제일",
        productName: "방울토마토",
        weightLabel: "1kg",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.12,
        price: 6900,
        originalPrice: 7841,
        status: "IN_PROGRESS",
        stepLabel: "2.5kg",
        progress: { currentKg: 8.0, maxKg: 15 },
        dDayLabel: "D-5",
        cancellable: true,
    },
    {
        id: "105",
        marketName: "진골마켓",
        productName: "양파",
        weightLabel: "3kg",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.09,
        price: 4450,
        originalPrice: 4890,
        status: "IN_PROGRESS",
        stepLabel: "5.0kg",
        progress: { currentKg: 11.0, maxKg: 15 },
        dDayLabel: "D-2",
        cancellable: true,
    },
    {
        id: "106",
        marketName: "푸른농원",
        productName: "브로콜리",
        weightLabel: "2송이",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.11,
        price: 3600,
        originalPrice: 4045,
        status: "IN_PROGRESS",
        stepLabel: "4.0송이",
        progress: { currentKg: 10.0, maxKg: 15 },
        dDayLabel: "D-3",
        cancellable: true,
    },
    {
        id: "107",
        marketName: "신선제일",
        productName: "영주 사과",
        weightLabel: "1.5kg",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.14,
        price: 7200,
        originalPrice: 8372,
        status: "IN_PROGRESS",
        stepLabel: "3.5kg",
        progress: { currentKg: 9.5, maxKg: 15 },
        dDayLabel: "D-1",
        cancellable: true,
    },
    {
        id: "108",
        marketName: "신선제일",
        productName: "배추",
        weightLabel: "1포기",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.07,
        price: 1750,
        originalPrice: 1882,
        status: "IN_PROGRESS",
        stepLabel: "7포기",
        progress: { currentKg: 10.0, maxKg: 15 },
        dDayLabel: "D-4",
        cancellable: true,
    },
    {
        id: "109",
        marketName: "진골마켓",
        productName: "파프리카 혼합",
        weightLabel: "1kg",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.13,
        price: 6100,
        originalPrice: 7011,
        status: "IN_PROGRESS",
        stepLabel: "4.0kg",
        progress: { currentKg: 8.5, maxKg: 15 },
        dDayLabel: "D-2",
        cancellable: true,
    },
    {
        id: "110",
        marketName: "푸른농원",
        productName: "오이",
        weightLabel: "5개",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.06,
        price: 3900,
        originalPrice: 4149,
        status: "IN_PROGRESS",
        stepLabel: "5개",
        progress: { currentKg: 11.5, maxKg: 15 },
        dDayLabel: "D-3",
        cancellable: true,
    },
    {
        id: "111",
        marketName: "푸른농원",
        productName: "달걀",
        weightLabel: "30구",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.05,
        price: 6480,
        originalPrice: 6821,
        status: "IN_PROGRESS",
        stepLabel: "2.0판",
        progress: { currentKg: 10.0, maxKg: 15 },
        dDayLabel: "D-5",
        cancellable: true,
    },
    {
        id: "112",
        marketName: "진골마켓",
        productName: "찹쌀",
        weightLabel: "2kg",
        imageUrl:
            "https://www.saenong.com/assets/upload/detailimage1/20240709_7874794413310.jpg",
        discountRate: 0.09,
        price: 7900,
        originalPrice: 8681,
        status: "IN_PROGRESS",
        stepLabel: "6.0kg",
        progress: { currentKg: 12.5, maxKg: 15 },
        dDayLabel: "D-2",
        cancellable: true,
    },
];
