const deadlineItems = [
  {
    id: 1,
    marketId: 2,
    productId: 204,
    marketName: "구미새마을중앙시장",
    name: "친환경 청양고추",
    weight: "150g~",
    originalPrice: 2600,
    discountRate: 29,
    discountedPrice: 1846,
    rating: 4.83,
    reviewCount: 9,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 2,
    marketId: 6,
    productId: 603,
    marketName: "원평시장",
    name: "국내산 토마토",
    weight: "1kg~",
    originalPrice: 4800,
    discountRate: 27,
    discountedPrice: 3504,
    rating: 4.79,
    reviewCount: 14,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 3,
    marketId: 9,
    productId: 905,
    marketName: "형곡시장",
    name: "국내산 감자",
    weight: "3kg~",
    originalPrice: 6400,
    discountRate: 25,
    discountedPrice: 4800,
    rating: 4.78,
    reviewCount: 13,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 4,
    marketId: 1,
    productId: 105,
    marketName: "신평시장",
    name: "국내산 양파",
    weight: "1.5kg~",
    originalPrice: 4200,
    discountRate: 22,
    discountedPrice: 3276,
    rating: 4.68,
    reviewCount: 19,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 5,
    marketId: 8,
    productId: 802,
    marketName: "옥계시장",
    name: "국내산 로메인",
    weight: "300g~",
    originalPrice: 3000,
    discountRate: 21,
    discountedPrice: 2370,
    rating: 4.74,
    reviewCount: 9,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 6,
    marketId: 5,
    productId: 505,
    marketName: "선산봉황시장",
    name: "국내산 당근",
    weight: "1kg~",
    originalPrice: 3800,
    discountRate: 18,
    discountedPrice: 3116,
    rating: 4.77,
    reviewCount: 13,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
];

export default deadlineItems;
