const deadlineItems = [
  {
    id: 1,
    shopId: 102,
    productId: 10204,
    marketName: "새마을 채소가게",
    name: "친환경 청양고추",
    weight: "150g~",
    originalPrice: 2600,
    discountRate: 29,
    discountedPrice: 1846,
    rating: 4.83,
    reviewCount: 9,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 2,
    shopId: 106,
    productId: 10603,
    marketName: "원평 채소가게",
    name: "국내산 토마토",
    weight: "1kg~",
    originalPrice: 4800,
    discountRate: 27,
    discountedPrice: 3504,
    rating: 4.79,
    reviewCount: 14,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 3,
    shopId: 109,
    productId: 10905,
    marketName: "형곡 야채가게",
    name: "국내산 감자",
    weight: "3kg~",
    originalPrice: 6400,
    discountRate: 25,
    discountedPrice: 4800,
    rating: 4.78,
    reviewCount: 13,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 4,
    shopId: 101,
    productId: 10105,
    marketName: "신평 과일가게",
    name: "국내산 양파",
    weight: "1.5kg~",
    originalPrice: 4200,
    discountRate: 22,
    discountedPrice: 3276,
    rating: 4.68,
    reviewCount: 19,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 5,
    shopId: 108,
    productId: 10802,
    marketName: "옥계 농산물가게",
    name: "국내산 로메인",
    weight: "300g~",
    originalPrice: 3000,
    discountRate: 21,
    discountedPrice: 2370,
    rating: 4.74,
    reviewCount: 9,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 6,
    shopId: 105,
    productId: 10505,
    marketName: "선산봉황 과일가게",
    name: "국내산 당근",
    weight: "1kg~",
    originalPrice: 3800,
    discountRate: 18,
    discountedPrice: 3116,
    rating: 4.77,
    reviewCount: 13,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
];

export default deadlineItems;
