const recommendedItems = [
  {
    id: 1,
    name: "국내산 흙당근",
    weight: "1.5kg~",
    price: 3000,
    originalPrice: 3780,
    discount: 21,
    rating: 4.82,
    reviews: 17,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 2,
    name: "국내산 감자",
    weight: "2kg~",
    price: 4800,
    originalPrice: 5600,
    discount: 14,
    rating: 4.74,
    reviews: 25,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 3,
    name: "국내산 양파",
    weight: "1kg~",
    price: 2500,
    originalPrice: 3000,
    discount: 17,
    rating: 4.61,
    reviews: 19,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 4,
    name: "국내산 마늘",
    weight: "500g~",
    price: 3800,
    originalPrice: 4600,
    discount: 17,
    rating: 4.91,
    reviews: 11,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 5,
    name: "국내산 대파",
    weight: "1kg~",
    price: 2900,
    originalPrice: 3500,
    discount: 17,
    rating: 4.76,
    reviews: 20,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 6,
    name: "친환경 상추",
    weight: "300g~",
    price: 1800,
    originalPrice: 2200,
    discount: 18,
    rating: 4.85,
    reviews: 8,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 7,
    name: "친환경 깻잎",
    weight: "200g~",
    price: 2100,
    originalPrice: 2600,
    discount: 19,
    rating: 4.77,
    reviews: 13,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 8,
    name: "국내산 무",
    weight: "1개",
    price: 3200,
    originalPrice: 3900,
    discount: 18,
    rating: 4.62,
    reviews: 9,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 9,
    name: "국내산 애호박",
    weight: "1개",
    price: 2800,
    originalPrice: 3500,
    discount: 20,
    rating: 4.71,
    reviews: 10,
    liked: false,
    imageUrl: "/images/carrot.jpg",
  },
  {
    id: 10,
    name: "국내산 청양고추",
    weight: "200g~",
    price: 2300,
    originalPrice: 2800,
    discount: 18,
    rating: 4.79,
    reviews: 12,
    liked: true,
    imageUrl: "/images/carrot.jpg",
  },
];

export default recommendedItems;
