// src/components/db/seller-sales.js

const IMG =
    "https://www.groworganic.com/cdn/shop/articles/Carrots5.png?v=1751040285";

const SALES = [
    {
        productId: 3,
        name: "제주 당근 5kg",
        unit: "KG",
        originalPricePerBaseUnit: 3200.0,
        stock: 500.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 7,
        groupBuyStatus: "OPEN",
        targetQty: 500.0,
        currentQty: 10.0,
        maxDiscountPercent: 25.0,
        stageCount: 3,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 0.0,
        appliedUnitPrice: 3200,
        remainingToNextStage: 115.0,
    },
    {
        productId: 4,
        name: "유기농 당근 1kg",
        unit: "KG",
        originalPricePerBaseUnit: 5290.0,
        stock: 120.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 8,
        groupBuyStatus: "READY_FOR_PICKUP",
        targetQty: 80.0,
        currentQty: 45.0,
        maxDiscountPercent: 20.0,
        stageCount: 3,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 15.0,
        appliedUnitPrice: 4500,
        remainingToNextStage: 10.0,
    },
    {
        productId: 5,
        name: "신선한 양파 3kg",
        unit: "KG",
        originalPricePerBaseUnit: 10150.0,
        stock: 300.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 9,
        groupBuyStatus: "IN_PROGRESS",
        targetQty: 120.0,
        currentQty: 55.0,
        maxDiscountPercent: 22.0,
        stageCount: 4,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 12.0,
        appliedUnitPrice: 8920,
        remainingToNextStage: 5.0,
    },
    {
        productId: 6,
        name: "아삭한 오이 1kg",
        unit: "KG",
        originalPricePerBaseUnit: 3800.0,
        stock: 200.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 10,
        groupBuyStatus: "OPEN",
        targetQty: 60.0,
        currentQty: 8.0,
        maxDiscountPercent: 12.0,
        stageCount: 3,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 8.0,
        appliedUnitPrice: 3500,
        remainingToNextStage: 4.0,
    },
    {
        productId: 7,
        name: "방울토마토 1.5kg",
        unit: "KG",
        originalPricePerBaseUnit: 9500.0,
        stock: 150.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 11,
        groupBuyStatus: "IN_PROGRESS",
        targetQty: 90.0,
        currentQty: 27.0,
        maxDiscountPercent: 25.0,
        stageCount: 3,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 20.0,
        appliedUnitPrice: 7600,
        remainingToNextStage: 3.0,
    },
    {
        productId: 8,
        name: "단호박 2kg",
        unit: "KG",
        originalPricePerBaseUnit: 10000.0,
        stock: 80.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 12,
        groupBuyStatus: "COMPLETED",
        targetQty: 50.0,
        currentQty: 50.0,
        maxDiscountPercent: 25.0,
        stageCount: 3,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 18.0,
        appliedUnitPrice: 8200,
        remainingToNextStage: 0.0,
    },
    {
        productId: 9,
        name: "향긋한 대파 1kg",
        unit: "KG",
        originalPricePerBaseUnit: 2950.0,
        stock: 60.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 13,
        groupBuyStatus: "CLOSED",
        targetQty: 40.0,
        currentQty: 40.0,
        maxDiscountPercent: 10.0,
        stageCount: 2,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 5.0,
        appliedUnitPrice: 2800,
        remainingToNextStage: 0.0,
    },
    {
        productId: 10,
        name: "아삭한 상추 0.8kg",
        unit: "KG",
        originalPricePerBaseUnit: 4800.0,
        stock: 70.0,
        imageUrl: IMG,
        storeId: 1,
        storeName: "테스트 상점",
        unitType: "KG",
        groupBuyId: 14,
        groupBuyStatus: "CANCELLED",
        targetQty: 20.0,
        currentQty: 12.0,
        maxDiscountPercent: 18.0,
        stageCount: 2,
        startAt: null,
        endAt: null,
        currentDiscountPercent: 14.0,
        appliedUnitPrice: 4100,
        remainingToNextStage: 0.0,
    },
];

export default SALES;
