export const SHOPS = [
    {
        id: 1,
        shopId: 101,
        name: "신평 과일가게",
        location: "경북 구미시 신평동",
        lat: 36.1089,
        lng: 128.3445,
        products: [
            {
                id: 10101,
                name: "국내산 흑당근",
                weight: "1.5kg~",
                originalPrice: 5000,
                discountRate: 21,
                discountedPrice: 3950,
                rating: 4.82,
                reviewCount: 17,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10102,
                name: "국내산 대파",
                weight: "1kg~",
                originalPrice: 3500,
                discountRate: 25,
                discountedPrice: 2625,
                rating: 4.76,
                reviewCount: 22,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10103,
                name: "국내산 감자",
                weight: "3kg~",
                originalPrice: 7200,
                discountRate: 28,
                discountedPrice: 5184,
                rating: 4.92,
                reviewCount: 30,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10104,
                name: "친환경 오이",
                weight: "3개입",
                originalPrice: 4000,
                discountRate: 20,
                discountedPrice: 3200,
                rating: 4.85,
                reviewCount: 15,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10105,
                name: "국내산 양파",
                weight: "1.5kg~",
                originalPrice: 4200,
                discountRate: 22,
                discountedPrice: 3276,
                rating: 4.68,
                reviewCount: 19,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 2,
        shopId: 102,
        name: "새마을 채소가게",
        location: "경북 구미시 원평동",
        lat: 36.1161,
        lng: 128.3457,
        products: [
            {
                id: 10201,
                name: "국내산 방울토마토",
                weight: "500g~",
                originalPrice: 4800,
                discountRate: 30,
                discountedPrice: 3360,
                rating: 4.77,
                reviewCount: 18,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10202,
                name: "국내산 깻잎",
                weight: "200g~",
                originalPrice: 2800,
                discountRate: 24,
                discountedPrice: 2128,
                rating: 4.74,
                reviewCount: 12,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10203,
                name: "국내산 무",
                weight: "1개",
                originalPrice: 3100,
                discountRate: 26,
                discountedPrice: 2294,
                rating: 4.79,
                reviewCount: 11,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10204,
                name: "친환경 청양고추",
                weight: "150g~",
                originalPrice: 2600,
                discountRate: 29,
                discountedPrice: 1846,
                rating: 4.83,
                reviewCount: 9,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10205,
                name: "국내산 애호박",
                weight: "1개",
                originalPrice: 2800,
                discountRate: 21,
                discountedPrice: 2212,
                rating: 4.76,
                reviewCount: 13,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 3,
        shopId: 103,
        name: "공단 청과점",
        location: "경북 구미시 공단동",
        lat: 36.1125,
        lng: 128.3848,
        products: [
            {
                id: 10301,
                name: "국내산 사과",
                weight: "5개입",
                originalPrice: 6500,
                discountRate: 15,
                discountedPrice: 5525,
                rating: 4.88,
                reviewCount: 21,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10302,
                name: "국내산 배추",
                weight: "1포기",
                originalPrice: 3500,
                discountRate: 18,
                discountedPrice: 2870,
                rating: 4.8,
                reviewCount: 14,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10303,
                name: "친환경 시금치",
                weight: "300g~",
                originalPrice: 3500,
                discountRate: 27,
                discountedPrice: 2555,
                rating: 4.81,
                reviewCount: 14,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10304,
                name: "국내산 마늘",
                weight: "1망",
                originalPrice: 7000,
                discountRate: 20,
                discountedPrice: 5600,
                rating: 4.85,
                reviewCount: 19,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10305,
                name: "국내산 고구마",
                weight: "2kg~",
                originalPrice: 8000,
                discountRate: 25,
                discountedPrice: 6000,
                rating: 4.9,
                reviewCount: 22,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 4,
        shopId: 104,
        name: "금오 버섯가게",
        location: "경북 구미시 금오동",
        lat: 36.1155,
        lng: 128.3301,
        products: [
            {
                id: 10401,
                name: "국내산 새송이",
                weight: "400g~",
                originalPrice: 3600,
                discountRate: 22,
                discountedPrice: 2808,
                rating: 4.84,
                reviewCount: 12,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10402,
                name: "국내산 상추",
                weight: "300g~",
                originalPrice: 2400,
                discountRate: 20,
                discountedPrice: 1920,
                rating: 4.7,
                reviewCount: 10,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10403,
                name: "국내산 가지",
                weight: "3개입",
                originalPrice: 3000,
                discountRate: 26,
                discountedPrice: 2220,
                rating: 4.73,
                reviewCount: 9,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10404,
                name: "친환경 미나리",
                weight: "300g~",
                originalPrice: 3200,
                discountRate: 25,
                discountedPrice: 2400,
                rating: 4.86,
                reviewCount: 8,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10405,
                name: "국내산 청경채",
                weight: "300g~",
                originalPrice: 2600,
                discountRate: 23,
                discountedPrice: 2002,
                rating: 4.72,
                reviewCount: 7,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 5,
        shopId: 105,
        name: "선산봉황 과일가게",
        location: "경북 구미시 선산읍",
        lat: 36.243,
        lng: 128.3005,
        products: [
            {
                id: 10501,
                name: "국내산 배",
                weight: "5개입",
                originalPrice: 7000,
                discountRate: 21,
                discountedPrice: 5530,
                rating: 4.81,
                reviewCount: 16,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10502,
                name: "국내산 파프리카",
                weight: "3개입",
                originalPrice: 4200,
                discountRate: 24,
                discountedPrice: 3192,
                rating: 4.76,
                reviewCount: 12,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10503,
                name: "국내산 양배추",
                weight: "1통",
                originalPrice: 3500,
                discountRate: 20,
                discountedPrice: 2800,
                rating: 4.69,
                reviewCount: 11,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10504,
                name: "친환경 부추",
                weight: "300g~",
                originalPrice: 2800,
                discountRate: 22,
                discountedPrice: 2184,
                rating: 4.8,
                reviewCount: 9,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10505,
                name: "국내산 당근",
                weight: "1kg~",
                originalPrice: 3800,
                discountRate: 18,
                discountedPrice: 3116,
                rating: 4.77,
                reviewCount: 13,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 6,
        shopId: 106,
        name: "원평 채소가게",
        location: "경북 구미시 원평동",
        lat: 36.1012,
        lng: 128.3566,
        products: [
            {
                id: 10601,
                name: "국내산 버섯 모둠",
                weight: "500g~",
                originalPrice: 5000,
                discountRate: 25,
                discountedPrice: 3750,
                rating: 4.86,
                reviewCount: 15,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10602,
                name: "국내산 브로콜리",
                weight: "1개",
                originalPrice: 3600,
                discountRate: 19,
                discountedPrice: 2916,
                rating: 4.74,
                reviewCount: 10,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10603,
                name: "국내산 토마토",
                weight: "1kg~",
                originalPrice: 4800,
                discountRate: 27,
                discountedPrice: 3504,
                rating: 4.79,
                reviewCount: 14,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10604,
                name: "친환경 당근",
                weight: "1kg~",
                originalPrice: 4000,
                discountRate: 23,
                discountedPrice: 3080,
                rating: 4.75,
                reviewCount: 9,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10605,
                name: "국내산 콩나물",
                weight: "500g~",
                originalPrice: 1800,
                discountRate: 20,
                discountedPrice: 1440,
                rating: 4.7,
                reviewCount: 8,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 7,
        shopId: 107,
        name: "인동 채소가게",
        location: "경북 구미시 인동동",
        lat: 36.1048,
        lng: 128.4089,
        products: [
            {
                id: 10701,
                name: "국내산 깐마늘",
                weight: "500g~",
                originalPrice: 7600,
                discountRate: 28,
                discountedPrice: 5472,
                rating: 4.89,
                reviewCount: 18,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10702,
                name: "국내산 양파망",
                weight: "1kg~",
                originalPrice: 3800,
                discountRate: 21,
                discountedPrice: 3002,
                rating: 4.72,
                reviewCount: 12,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10703,
                name: "국내산 애느타리버섯",
                weight: "300g~",
                originalPrice: 2600,
                discountRate: 20,
                discountedPrice: 2080,
                rating: 4.73,
                reviewCount: 10,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10704,
                name: "친환경 시금치",
                weight: "300g~",
                originalPrice: 3200,
                discountRate: 26,
                discountedPrice: 2368,
                rating: 4.8,
                reviewCount: 9,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10705,
                name: "국내산 단호박",
                weight: "1개",
                originalPrice: 4200,
                discountRate: 22,
                discountedPrice: 3276,
                rating: 4.78,
                reviewCount: 11,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 8,
        shopId: 108,
        name: "옥계 농산물가게",
        location: "경북 구미시 옥계동",
        lat: 36.1234,
        lng: 128.4211,
        products: [
            {
                id: 10801,
                name: "국내산 무청",
                weight: "1단",
                originalPrice: 2500,
                discountRate: 20,
                discountedPrice: 2000,
                rating: 4.68,
                reviewCount: 7,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10802,
                name: "국내산 로메인",
                weight: "300g~",
                originalPrice: 3000,
                discountRate: 21,
                discountedPrice: 2370,
                rating: 4.74,
                reviewCount: 9,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10803,
                name: "국내산 새송이 버섯",
                weight: "400g~",
                originalPrice: 3400,
                discountRate: 24,
                discountedPrice: 2584,
                rating: 4.75,
                reviewCount: 8,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10804,
                name: "친환경 열무",
                weight: "1단",
                originalPrice: 2800,
                discountRate: 25,
                discountedPrice: 2100,
                rating: 4.79,
                reviewCount: 10,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10805,
                name: "국내산 청양고추",
                weight: "200g~",
                originalPrice: 2700,
                discountRate: 19,
                discountedPrice: 2187,
                rating: 4.76,
                reviewCount: 9,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 9,
        shopId: 109,
        name: "형곡 야채가게",
        location: "경북 구미시 형곡동",
        lat: 36.1189,
        lng: 128.3602,
        products: [
            {
                id: 10901,
                name: "국내산 깻잎",
                weight: "200g~",
                originalPrice: 2600,
                discountRate: 22,
                discountedPrice: 2028,
                rating: 4.73,
                reviewCount: 10,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10902,
                name: "국내산 오이",
                weight: "3개입",
                originalPrice: 3900,
                discountRate: 20,
                discountedPrice: 3120,
                rating: 4.71,
                reviewCount: 8,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10903,
                name: "국내산 대파",
                weight: "1kg~",
                originalPrice: 3300,
                discountRate: 23,
                discountedPrice: 2541,
                rating: 4.74,
                reviewCount: 11,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10904,
                name: "친환경 샐러리",
                weight: "1단",
                originalPrice: 3700,
                discountRate: 24,
                discountedPrice: 2812,
                rating: 4.72,
                reviewCount: 7,
                liked: false,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 10905,
                name: "국내산 감자",
                weight: "3kg~",
                originalPrice: 6400,
                discountRate: 25,
                discountedPrice: 4800,
                rating: 4.78,
                reviewCount: 13,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
    {
        id: 10,
        shopId: 110,
        name: "진평 채소가게",
        location: "경북 구미시 진평동",
        lat: 36.0911,
        lng: 128.3715,
        products: [
            {
                id: 11001,
                name: "국내산 방울토마토",
                weight: "1kg~",
                originalPrice: 5000,
                discountRate: 28,
                discountedPrice: 3600,
                rating: 4.83,
                reviewCount: 16,
                liked: true,
                imageUrl: "/images/carrot.jpg",
                progressCurrent: 3,
                progressMax: 15,
            },
            {
                id: 11002,
                name: "국내산 가지",
                weight: "3개입",
                originalPrice: 3100,
                discountRate: 20,
                discountedPrice: 2480,
                rating: 4.7,
                reviewCount: 12,
                progressCurrent: 3,
                progressMax: 15,
            },
        ],
    },
];

export default SHOPS;
